// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbEWmHx6R55WVmhSJGpRQLOLlL6vdwYk',
    appId: '1:142535428939:web:7b422a6f80b50e2b5876ce',
    messagingSenderId: '142535428939',
    projectId: 'techigh-tiktok-dev-cli',
    authDomain: 'techigh-tiktok-dev-cli.firebaseapp.com',
    storageBucket: 'techigh-tiktok-dev-cli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdk8aaRIB3nUITC2ZhVh4pdjQRiOduudU',
    appId: '1:142535428939:android:8e11ca8709087e8a5876ce',
    messagingSenderId: '142535428939',
    projectId: 'techigh-tiktok-dev-cli',
    storageBucket: 'techigh-tiktok-dev-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlSsH9TN60c5Uy-iFWqP-Js_ZmHKFzyo',
    appId: '1:142535428939:ios:63e24189fe9a96025876ce',
    messagingSenderId: '142535428939',
    projectId: 'techigh-tiktok-dev-cli',
    storageBucket: 'techigh-tiktok-dev-cli.appspot.com',
    iosClientId: '142535428939-h0adqv5dj4p7c4c82qoltutu219br742.apps.googleusercontent.com',
    iosBundleId: 'com.techigh.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLlSsH9TN60c5Uy-iFWqP-Js_ZmHKFzyo',
    appId: '1:142535428939:ios:63e24189fe9a96025876ce',
    messagingSenderId: '142535428939',
    projectId: 'techigh-tiktok-dev-cli',
    storageBucket: 'techigh-tiktok-dev-cli.appspot.com',
    iosClientId: '142535428939-h0adqv5dj4p7c4c82qoltutu219br742.apps.googleusercontent.com',
    iosBundleId: 'com.techigh.tiktok',
  );
}
